name: moore
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1-alpha+1

environment:
  sdk: ^3.11.0-221.0.dev

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.3

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  phosphor_flutter: ^2.1.0
  go_router: ^17.0.1
  playerctl: ^1.2.0
  pulseaudio: ^0.0.8
  flutter_local_notifications: ^19.5.0
  dbus: ^0.7.11
  shared_preferences: ^2.5.4

  intl: any
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  generate: true
